# Generated by Django 4.1.7 on 2023-04-01 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0004_particicpant'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='Particicpant',
            field=models.ManyToManyField(blank=True, null=True, to='meetups.particicpant'),
        ),
    ]
